/**
 * 图谱数据源
 */

export const data = [
        {
            id:1,
            name:'线性方程组',
            categary:'百科',
            children:[
                {
                    id:11,
                    categary:'',
                    name:'消元法',
                    children:[
                        {
                            id:111,
                            name:'线性方程的初等变换',
                            categary:'',
                        },
                        {
                            id:112,
                            name:'解一般线性方程组',
                            categary:'用法',
                        }
                    ],
                },
                {
                    id:12,
                    categary:'',
                    name:'n维向量空间',
                    children:[
                        {
                            id:121,
                            name:'向量的分量',
                            categary:'',
                        },
                        {
                            id:122,
                            name:'向量的运算性质',
                            categary:'用法',
                            children:[
                                {
                                    id:1221,
                                    name:'向量相等',
                                    categary:'',
                                },
                                {
                                    id:1222,
                                    name:'向量的和',
                                    categary:'用法',
                                },
                                {
                                    id:1223,
                                    name:'零向量与负向量',
                                    categary:'用法',
                                },
                                {
                                    id:1224,
                                    name:'向量的数量乘积',
                                    categary:'用法',
                                },
                            ],
                        }
                    ],
                },
                {
                    id:13,
                    name:'线性相关性',
                        categary:'应用',
                        children:[
                            {
                                id:131,
                                name:'向量的线性组合',
                                categary:'线性组合',
                            },
                            {
                                id:132,
                                name:'向量组间的等价',
                                categary:'直接计算',
                            },
                            {
                                id:133,
                                name:'向量组间的线性相关',
                                categary:'直接计算',
                            },
                            {
                                id:134,
                                name:'向量组间的线性无关',
                                categary:'直接计算',
                            },
                            {
                                id:135,
                                name:'极大线性无关组',
                                categary:'直接计算',
                            },
                            {
                                id:136,
                                name:'向量组的秩',
                                categary:'直接计算',
                            },
                        ]
                    
                },
                {
                    id:14,
                    name:'矩阵的秩',
                    categary:'',
                    children:[
                        {
                            id:141,
                            name:'行秩与列秩',
                            categary:''
                        },
                        {
                            id:142,
                            name:'矩阵中秩的定义',
                            categary:''
                        },
                        {
                            id:143,
                            name:'秩的相关性质',
                            categary:'',
                            children:[
                                {
                                    id:1431,
                                    name:'秩与列秩、行秩之间的关系',
                                    categary:''
                                },
                                {
                                    id:1432,
                                    name:'矩阵的初等变换与秩',
                                    categary:''
                                },
                            ]
                        },
                        {
                            id:144,
                            name:'齐次线性方程组的非零解',
                            categary:''
                        },
                        {
                            id:145,
                            name:'克拉默法则及其逆定理',
                            categary:''
                        },
                    ]
                },
                {
                    id:15,
                    name:'线性方程组有解判别定理',
                    categary:'',
                },
                {
                    id:16,
                    name:'线性方程组解的结构',
                    categary:'',
                    children:[
                        {
                            id:161,
                            name:'齐次线性方程组解的集合的重要性质',
                            categary:'',
                            children:[
                                {
                                    id:1611,
                                    name:'两个解的和还是方程组的解',
                                    categary:''
                                },
                                {
                                    id:1612,
                                    name:'一个解的倍数还是方程组的解',
                                    categary:''
                                },
                            ]
                        },
                        {
                            id:162,
                            name:'齐次方程组的基础解系',
                            categary:'',
                        },
                        {
                            id:163,
                            name:'一般线性方程组解的结构',
                            categary:'',
                        },
                    ]
                },
            ]
        },
    
        {
            id:2,
            name:'矩阵2',
            categary:'百科',
            children:[
                {
                    id:21,
                    categary:'',
                    name:'矩阵的概念2.1',
                    children:[
                        {
                            id:211,
                            name:'矩阵的定义与矩阵的秩2.1.1',
                            categary:'',
                            
                        },
                        {
                            id:212,
                            name:'特殊矩阵的类型2.1.2',
                            categary:'用法',
                            children:[
                                {
                                    id:2121,
                                    name:'行矩阵与列矩阵2.1.2.1',
                                        categary:'',
                                        children:[
                                            {
                                                id:21211,
                                                name:'行矩阵2.1.2.1.1',
                                                categary:'',
                                            },
                                            {
                                                id:21212,
                                                name:'列矩阵2.1.2.1.2',
                                                categary:'',
                                            },
                                        ]
                                    
                                },
                                {
                                    id:2122,
                                    name:'零矩阵2.1.2.2',
                                    categary:'用法',
                                },
                                {
                                    id:2123,
                                    name:'数量矩阵2.1.2.3',
                                    categary:'用法',
                                    children:[
                                        {
                                            id:21231,
                                            name:'单位矩阵2.1.2.3.1',
                                            categary:'用法',
                                        },
                                        {
                                            id:21232,
                                            name:'普通数量矩2.1.2.3.2',
                                            categary:'用法',
                                        },
                                    ],
                                },
                                {
                                    id:2124,
                                    name:'对角矩阵2.1.2.4',
                                    categary:'用法',
                                },
                                {
                                    id:2125,
                                    name:'三角矩阵2.1.2.5',
                                    categary:'用法',
                                },
                            ],
                        }
                    ],
                },
                {
                    id:22,
                    categary:'',
                    name:'矩阵的运算2.2',
                    children:[
                        {
                            id:221,
                            name:'矩阵相等2.2.1',
                                categary:'',
                                children:[
                                    {
                                        id:2211,
                                        name:'同型矩阵2.2.1.1',
                                        categary:'',
                                    },
                                    {
                                        id:2212,
                                        name:'对应元素相等2.2.1.2',
                                        categary:'',
                                    },
                                ],
                                
                        },
                        {
                            id:222,
                            name:'矩阵加法2.2.2',
                                categary:'',
                                children:[
                                    {
                                        id:2221,
                                        name:'矩阵加法的定义2.2.2.1',
                                        categary:'',
                                    },
                                    {
                                        id:2222,
                                        name:'矩阵加法的运算规律2.2.2.2',
                                            categary:'',
                                            children:[
                                                {
                                                    id:22221,
                                                    name:'矩阵加法的交换律2.2.2.2.1',
                                                    categary:'',
                                                },
                                                {
                                                    id:22222,
                                                    name:'矩阵加法的结合律2.2.2.2.2',
                                                    categary:'',
                                                },
                                                {
                                                    id:22223,
                                                    name:'矩阵加法的零矩阵2.2.2.2.3',
                                                    categary:'',
                                                },
                                                {
                                                    id:22224,
                                                    name:'矩阵的负矩阵2.2.2.2.4',
                                                    categary:'',
                                                },
                                            ],
                                    },
                                    {
                                        id:2223,
                                        name:'矩阵加法的秩的关系2.2.2.3',
                                        categary:'',
                                    },
                                ],
                        },
                        {
                            id:223,
                            name:'数量乘法2.2.3',
                                categary:'',
                                children:[
                                    {
                                        id:2231,
                                        name:'数量乘法的定义2.2.3.1',
                                        categary:'',
                                    },
                                    {
                                        id:2232,
                                        name:'数量乘法的运算规律2.2.3.2',
                                            categary:'',
                                            children:[
                                                {
                                                    id:22321,
                                                    name:'分配律2.2.3.2.1',
                                                    categary:'',
                                                },
                                                {
                                                    id:22322,
                                                    name:'对数乘的结合性2.2.3.2.2',
                                                    categary:'',
                                                },
                                            ],
                                    },
                                ],
                        },
                        {
                            id:224,
                            name:'矩阵乘法2.2.4',
                                categary:'',
                                children:[
                                    {
                                        id:2241,
                                        name:'矩阵乘法的定义2.2.4.1',
                                        categary:'',
                                    },
                                    {
                                        id:2242,
                                        name:'矩阵乘法的运算规律2.2.4.2',
                                            categary:'',
                                            children:[
                                                {
                                                    id:22421,
                                                    name:'乘法左分配律2.2.4.2.1',
                                                    categary:'',
                                                },
                                                {
                                                    id:22422,
                                                    name:'乘法右分配律2.2.4.2.2',
                                                    categary:'',
                                                },
                                                {
                                                    id:22423,
                                                    name:'乘法结合律2.2.4.2.3',
                                                    categary:'',
                                                },
                                            ],
                                    },
                                    {
                                        id:2243,
                                        name:'方阵的幂2.2.4.3',
                                        categary:'',
                                    },
                                    {
                                        id:2244,
                                        name:'矩阵乘法的行列式与秩的关系2.2.4.4',
                                        categary:'',
                                    },
                                    {
                                        id:2245,
                                        name:'矩阵乘法与线性变换2.2.4.5',
                                        categary:'',
                                    },
                                ],
                        },
                        {
                            id:225,
                            name:'矩阵转置2.2.5',
                                categary:'',
                                children:[
                                    {
                                        id:2251,
                                        name:'矩阵转置的定义2.2.5.1',
                                        categary:'',
                                    },
                                    {
                                        id:2252,
                                        name:'对称矩阵2.2.5.2',
                                        categary:'',
                                    },
                                    {
                                        id:2253,
                                        name:'反对称矩阵2.2.5.3',
                                        categary:'',
                                    },
                                    {
                                        id:2254,
                                        name:'矩阵转置的运算规律2.2.5.4',
                                        categary:'',
                                    },
                                ],
                        },
                        {
                            id:226,
                            name:'矩阵的逆2.2.6',
                                categary:'',
                                children:[
                                    {
                                        id:2261,
                                        name:'矩阵的逆的定义2.2.6.1',
                                        categary:'',
                                    },
                                    {
                                        id:2262,
                                        name:'伴随矩阵2.2.6.2',
                                        categary:'',
                                    },
                                    {
                                        id:2263,
                                        name:'矩阵的逆的秩的关系2.2.6.3',
                                        categary:'',
                                    },
                                ],
                        },
                        {
                            id:227,
                            name:'矩阵变换与解线性方程组2.2.7',
                            categary:'',
                        },
                    ],
                },
                {
                    id:23,
                    name:'矩阵的分块2.3',
                        categary:'证明',
                        children:[
                            {
                                id:231,
                                name:'矩阵的分块的证明与准对角矩阵2.3.1',
                                categary:'',
                            },
                            {
                                id:232,
                                name:'矩阵的分块的应用2.3.2',
                                categary:'应用',
                                children:[
                                    {
                                        id:2321,
                                        name:'矩阵的分块在加法中的应用2.3.2.1',
                                        categary:''
                                    },
                                    {
                                        id:2322,
                                        name:'矩阵的分块在乘法中的应用2.3.2.2',
                                        categary:''
                                    },
                                    {
                                        id:2323,
                                        name:'矩阵的分块在矩阵转置中的应用2.3.2.3',
                                        categary:''
                                    },
                                    {
                                        id:2324,
                                        name:'矩阵的分块在逆矩阵中的应用2.3.2.4',
                                        categary:''
                                    },
                                ],
                            },
                        ]
                    
                },
                {
                    
                    id:24,
                    name:'初等矩阵与初等变换2.4',
                        categary:'',
                        children:[
                            {
                                id:241,
                                name:'行阶梯型2.4.1',
                                categary:'',
                            },
                            {
                                id:242,
                                name:'初等矩阵的定义2.4.2',
                                categary:'',
                            },
                            {
                                id:243,
                                name:'初等变换2.4.3',
                                    categary:'',
                                    children:[
                                        {
                                            id:2431,
                                            name:'初等行变换2.4.3.1',
                                            categary:'',
                                        },
                                        {
                                            id:2432,
                                            name:'初等列变换2.4.3.2',
                                            categary:'',
                                        },
                                        {
                                            id:2433,
                                            name:'行唯一的简化阶梯矩阵2.4.3.3',
                                            categary:'',
                                        },
                                    ]
                            },
                            {
                                id:244,
                                name:'初等变换与秩的关系2.4.4',
                                categary:'',
                            },
                        ]
                },
            ]
        },
        {
            id:3,
            name:'二次型3',
                categary:'百科', 
                children:[
                    {
                        id:31,
                        name:'二次型及其矩阵表示3.1',
                            categary:'', 
                            children:[
                                {
                                    id:311,
                                    name:'二次型的定义3.1.1',
                                        categary:'', 
                                },
                                {
                                    id:312,
                                    name:'二次型的性质3.1.2',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3121,
                                                name:'二次型的矩阵3.1.2.1',
                                                    categary:'', 
                                                    children:[
                                                        {
                                                            id:31211,
                                                            name:'二次型的矩阵表示3.1.2.1.1',
                                                                categary:'', 
                                                        },
                                                        {
                                                            id:31212,
                                                            name:'矩阵的合同变换3.1.2.1.2',
                                                                categary:'', 
                                                        },
                                                        {
                                                            id:31213,
                                                            name:'合同矩阵的性质3.1.2.1.3',
                                                                categary:'', 
                                                        },
                                                    ]
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:32,
                        name:'二次型的标准型3.2',
                            categary:'', 
                            children:[
                                {
                                    id:321,
                                    name:'二次型的定理3.2.1',
                                        categary:'', 
                                },
                                {
                                    id:322,
                                    name:'标准型转换3.2.2',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3221,
                                                name:'配方法3.2.2.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:3222,
                                                name:'矩阵法3.2.2.2',
                                                    categary:'', 
                                            },
                                        ]
                                }
                            ]
                    },
                    {
                        id:33,
                        name:'唯一性3.3',
                            categary:'', 
                            children:[
                                {
                                    id:331,
                                    name:'二次型的定理3.3.1',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3311,
                                                name:'二次型的规范形3.3.1.1',
                                                    categary:'', 
                                                    children:[
                                                        {
                                                            id:33111,
                                                            name:'复二次型的规范形3.3.1.1.1',
                                                                categary:'', 
                                                        },
                                                        {
                                                            id:33112,
                                                            name:'实二次型的规范形3.3.1.1.2',
                                                                categary:'', 
                                                        },
                                                    ]
                                            },
                                            {
                                                id:3312,
                                                name:'惯性定理的定义3.3.1.2',
                                                    categary:'', 
                                            },
                                            {
                                                id:3313,
                                                name:'对称矩阵的秩3.3.1.3',
                                                    categary:'', 
                                            },
                                        ]
                                }
                            ]
                    },
                    {
                        id:34,
                        name:'正定二次型3.4',
                            categary:'', 
                            children:[
                                {
                                    id:341,
                                    name:'正定实对称矩阵的定义3.4.1',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3411,
                                                name:'正定实二次型的充要条件3.4.1.1',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:342,
                                    name:'正定矩阵的推论3.4.2',
                                        categary:'', 
                                },
                                {
                                    id:343,
                                    name:'顺序主子式的定义3.4.3',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3431,
                                                name:'正定实二次型的充要条件3.4.3.1',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:344,
                                    name:'逆序主子式的定义3.4.4',
                                        categary:'', 
                                },
                                {
                                    id:345,
                                    name:'正定二次型的判别3.4.5',
                                        categary:'', 
                                },
                                {
                                    id:346,
                                    name:'负定二次型的定义3.4.6',
                                        categary:'', 
                                },
                                {
                                    id:347,
                                    name:'半正定二次型的定义3.4.7',
                                        categary:'', 
                                        children:[
                                            {
                                                id:3471,
                                                name:'半正定二次型的定理3.4.7.1',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:348,
                                    name:'半负定二次型的定义3.4.8',
                                        categary:'', 
                                },
                                {
                                    id:349,
                                    name:'不定二次型的定义3.4.9',
                                        categary:'', 
                                },
                            ]
                    },
                ]
        },
        {
            id:4,
            name:'线性空间4',
                categary:'百科', 
                children:[
                    {
                        id:41,
                        name:'集合与映射4.1',
                            categary:'', 
                            children:[
                                {
                                    id:411,
                                    name:'集合4.1.1',
                                        categary:'', 
                                        children:[
                                            {
                                                id:4111,
                                                name:'集合的概念4.1.1.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:4112,
                                                name:'集合的运算4.1.1.2',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:412,
                                    name:'映射4.1.2',
                                        categary:'', 
                                        children:[
                                            {
                                                id:4121,
                                                name:'映射的概念4.1.2.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:4122,
                                                name:'映射的运算4.1.2.2',
                                                    categary:'', 
                                            },
                                            {
                                                id:4123,
                                                name:'单射、满射与双射4.1.2.3',
                                                    categary:'', 
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:42,
                        name:'线性空间的定义和简单性质4.2',
                            categary:'', 
                            children:[
                                {
                                    id:421,
                                    name:'线性空间的定义4.2.1',
                                        categary:'', 
                                },
                                {
                                    id:422,
                                    name:'线性空间运算规则4.2.2',
                                        categary:'', 
                                        children:[
                                            {
                                                id:4221,
                                                name:'加法规则4.2.2.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:4222,
                                                name:'数量乘法规则4.2.2.2',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:423,
                                    name:'线性空间的简单性质4.2.3',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:43,
                        name:'基与坐标4.3',
                            categary:'', 
                            children:[
                                {
                                    id:431,
                                    name:'线性相关4.3.1',
                                        categary:'', 
                                },
                                {
                                    id:432,
                                    name:'基与坐标的定义4.3.2',
                                        categary:'', 
                                },
                                {
                                    id:433,
                                    name:'基的确定与线性空间的表示4.3.3',
                                        categary:'', 
                                },
                                {
                                    id:434,
                                    name:'基变换与坐标变换4.3.4',
                                        categary:'', 
                                        children:[
                                            {
                                                id:4341,
                                                name:'基变换4.3.4.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:4342,
                                                name:'坐标变换4.3.4.2',
                                                    categary:'', 
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:44,
                        name:'线性子空间4.4',
                            categary:'', 
                            children:[
                                {
                                    id:441,
                                    name:'线性子空间的定义4.4.1',
                                        categary:'', 
                                },
                                {
                                    id:442,
                                    name:'线性子空间的简单性质4.4.2',
                                        categary:'', 
                                },
                                {
                                    id:443,
                                    name:'子空间的运算4.4.3',
                                        categary:'', 
                                        children:[
                                            {
                                                id:4431,
                                                name:'子空间的交运算4.4.3.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:4432,
                                                name:'子空间的和运算4.4.3.2',
                                                    categary:'', 
                                            },
                                            {
                                                id:4433,
                                                name:'维数公式4.4.3.3',
                                                    categary:'', 
                                            },
                                        ]
                                },
                                {
                                    id:444,
                                    name:'子空间的直和4.4.4',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:45,
                        name:'线性空间的同构4.5',
                            categary:'', 
                            children:[
                                {
                                    id:451,
                                    name:'同构与同构映射的定义4.5.1',
                                        categary:'', 
                                },
                                {
                                    id:452,
                                    name:'同构映射的性质4.5.2',
                                        categary:'', 
                                },
                                {
                                    id:453,
                                    name:'同构的充要条件4.5.3',
                                        categary:'', 
                                },
                            ]
                    },
                ]
        },
        {
            id:5,
            name:'线性变换5',
                categary:'百科', 
                children:[
                    {
                        id:51,
                        name:'线性变换的定义5.1',
                            categary:'', 
                            children:[
                                {
                                    id:511,
                                    name:'线性变换的定义5.1.1',
                                        categary:'', 
                                        children:[
                                            {
                                                id:5111,
                                                name:'定义5.1.1.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:5112,
                                                name:'性质5.1.1.2',
                                                    categary:'', 
                                            },
                                            {
                                                id:5113,
                                                name:'特殊线性变换5.1.1.3',
                                                    categary:'', 
                                                    children:[
                                                        {
                                                            id:51131,
                                                            name:'恒等变换/单位变换5.1.1.3.1',
                                                                categary:'', 
                                                        },
                                                        {
                                                            id:51132,
                                                            name:'数乘变换5.1.1.3.2',
                                                                categary:'', 
                                                        },
                                                        {
                                                            id:51133,
                                                            name:'零变换5.1.1.3.3',
                                                                categary:'', 
                                                        },
                                                    ]
                                            },
                                        ]
                                }
                            ]
                    },
                    {
                        id:52,
                        name:'线性变换的运算5.2',
                            categary:'', 
                            children:[
                                {
                                    id:521,
                                    name:'乘积5.2.1',
                                        categary:'', 
                                },
                                {
                                    id:522,
                                    name:'加法与数乘5.2.2',
                                        categary:'', 
                                },
                                {
                                    id:523,
                                    name:'逆变换5.2.3',
                                        categary:'', 
                                },
                                {
                                    id:524,
                                    name:'线性变换的多项式5.2.4',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:53,
                        name:'二次型3',
                            categary:'', 
                            children:[
                                {
                                    id:531,
                                    name:'线性变换矩阵的定义5.3.1',
                                        categary:'', 
                                },
                                {
                                    id:532,
                                    name:'线性变换矩阵的定理5.3.2',
                                        categary:'', 
                                },
                                {
                                    id:533,
                                    name:'相似矩阵的定义5.3.3',
                                        categary:'', 
                                },
                                {
                                    id:534,
                                    name:'相似矩阵的性质5.3.4',
                                        categary:'', 
                                        children:[
                                            {
                                                id:5341,
                                                name:'自反性5.3.4.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:5342,
                                                name:'对称性5.3.4.2',
                                                    categary:'', 
                                            },
                                            {
                                                id:5343,
                                                name:'传递性5.3.4.3',
                                                    categary:'', 
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:54,
                        name:'特征值与特征向量5.4',
                            categary:'', 
                            children:[
                                {
                                    id:541,
                                    name:'特征值与特征向量的定义5.4.1',
                                        categary:'', 
                                },
                                {
                                    id:542,
                                    name:'特征多项式的定义5.4.2',
                                        categary:'', 
                                },
                                {
                                    id:543,
                                    name:'确定特征值与特征向量的方法5.4.3',
                                        categary:'', 
                                },
                                {
                                    id:544,
                                    name:'Hamilton-Cayley定理5.4.4',
                                        categary:'', 
                                        children:[
                                            {
                                                id:5441,
                                                name:'定理5.4.4.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:5442,
                                                name:'推论5.4.4.2',
                                                    categary:'', 
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:55,
                        name:'对角矩阵5.5',
                            categary:'', 
                            children:[
                                {
                                    id:551,
                                    name:'定理5.5.1',
                                        categary:'', 
                                },
                                {
                                    id:552,
                                    name:'推论5.5.2',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:56,
                        name:'线性变换的值域与核5.6',
                            categary:'', 
                            children:[
                                {
                                    id:561,
                                    name:'值域与核的定义5.6.1',
                                        categary:'', 
                                },
                                {
                                    id:562,
                                    name:'秩与零度的定义5.6.2',
                                        categary:'', 
                                },
                                {
                                    id:563,
                                    name:'定理5.6.3',
                                        categary:'', 
                                },
                                {
                                    id:564,
                                    name:'推论5.6.4',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:57,
                        name:'不变子空间5.7',
                            categary:'', 
                            children:[
                                {
                                    id:571,
                                    name:'不变子空间的定义5.7.1',
                                        categary:'', 
                                },
                                {
                                    id:572,
                                    name:'不变子空间的性质5.7.2',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:58,
                        name:'Jordan标准型5.8',
                            categary:'', 
                            children:[
                                {
                                    id:581,
                                    name:'Jordan块与Jordan标准型的定义5.8.1',
                                        categary:'', 
                                },
                                {
                                    id:582,
                                    name:'定理5.8.2',
                                        categary:'', 
                                },
                            ]
                    },
                ]
        },
        {
            id:6,
            name:'欧几里得空间6',
                categary:'百科', 
                children:[
                    {
                        id:61,
                        name:'欧几里得空间的定义与基本性质6.1',
                            categary:'', 
                            children:[
                                {
                                    id:611,
                                    name:'内积的定义与性质6.1.1',
                                        categary:'', 
                                },
                                {
                                    id:612,
                                    name:'长度的定义与性质6.1.2',
                                        categary:'', 
                                },
                                {
                                    id:613,
                                    name:'夹角的定义与性质6.1.3',
                                        categary:'', 
                                },
                                {
                                    id:614,
                                    name:'正交的定义与性质6.1.4',
                                        categary:'', 
                                },
                                {
                                    id:615,
                                    name:'度量矩阵的定义与性质6.1.5',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:62,
                        name:'标准正交基6.2',
                            categary:'', 
                            children:[
                                {
                                    id:621,
                                    name:'正交向量组的定义6.2.1',
                                        categary:'', 
                                },
                                {
                                    id:622,
                                    name:'正交基与标准正交基的定义6.2.2',
                                        categary:'', 
                                },
                                {
                                    id:623,
                                    name:'定理6.2.3',
                                        categary:'', 
                                },
                                {
                                    id:624,
                                    name:'Schmidt正交化过程6.2.4',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:63,
                        name:'同构6.3',
                            categary:'',
                            children:[
                                {
                                    id:631,
                                    name:'同构与同构映射的定义与性质6.3.1',
                                        categary:'', 
                                },
                            ] 
                    },
                    {
                        id:64,
                        name:'正交变换6.4',
                            categary:'', 
                            children:[
                                {
                                    id:641,
                                    name:'正交变换的定义6.4.1',
                                        categary:'', 
                                },
                                {
                                    id:642,
                                    name:'定理6.4.2',
                                        categary:'', 
                                },
                                {
                                    id:643,
                                    name:'分类6.4.3',
                                        categary:'', 
                                        children:[
                                            {
                                                id:6431,
                                                name:'第一类（旋转）6.4.3.1',
                                                    categary:'', 
                                            },
                                            {
                                                id:6432,
                                                name:'第二类6.4.3.2',
                                                    categary:'', 
                                            },
                                        ]
                                },
                            ]
                    },
                    {
                        id:65,
                        name:'子空间6.5',
                            categary:'', 
                            children:[
                                {
                                    id:651,
                                    name:'子空间与子空间正交及向量与子空间正交的定义6.5.1',
                                        categary:'', 
                                },
                                {
                                    id:652,
                                    name:'正交补的定义6.5.2',
                                        categary:'', 
                                },
                                {
                                    id:653,
                                    name:'定理与推论6.5.3',
                                        categary:'', 
                                },
                            ]
                    },
                    {
                        id:66,
                        name:'实对称矩阵的标准形6.6',
                            categary:'', 
                            children:[
                                {
                                    id:661,
                                    name:'对称变换的定义6.6.1',
                                        categary:'', 
                                },
                                {
                                    id:662,
                                    name:'正交矩阵的求法6.6.2',
                                        categary:'', 
                                },
                                {
                                    id:663,
                                    name:'定理6.6.3',
                                        categary:'', 
                                },
                            ]
                    },
                ]
        },
    ]
/**
 * 模糊查询大类
 * @param {*} name 
 */
export const search = (name)=>{
    return new Promise((resolve,reject)=>{
        let result = []
        let list = data.filter(item=>item.name.indexOf(name)>=0)
        if(list&&list.length>0){
            result = list||[]
        }
        if(result.length>0){
            resolve(result)
        }else{
            reject()
        }
    })
}

/**
 * 点击节点展开
 * @param {*} id 
 */
export const expendNodes = (id)=>{
    return new Promise((resolve,reject)=>{
        let totalList = []
        //拆除来所有的children到第一层
        data.forEach(item=>{
            getDeepChildrens(totalList,item,0)
        })

        let list = []
        for(let item of totalList){
            if(item.parentId.toString() === id){
                const {children,...reset} = item
                list.push({
                    ...reset
                })
            }
        }
        if(list.length>0){
            resolve(list)
        }else{
            reject()
        }
        
    })
    
}

/**
 * 递归数组,把所有children都拆出来到第一层
 * @param {*} list 
 * @param {*} item 
 */
function getDeepChildrens(list,item,parentId){
    const {children,...reset} =  item
    list.push(
        {
            ...reset,
            parentId,
        }
    )
    if(children&&children.length>0){
        children.forEach(child=>{
            getDeepChildrens(list,child,item.id)
        })
    }
}

/**
 * 分类数据
 */
export const categarys =  ["线性方程组","矩阵","二次型","线性空间","线性变换","欧几里得空间"]